apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storage.className }}
provisioner: {{ .Values.storage.provisioner }}
volumeBindingMode: {{ .Values.storage.volumeBindingMode }}
