apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployment.floopybird.name }}-mongodb-credentials
  namespace: {{ .Values.deployment.floopybird.namespace }}
  annotations:
    avp.kubernetes.io/path: "secrets/data/avp"
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  mongodb-root-user: <MONGO_USERNAME>
  mongodb-root-password: <MONGO_PASSWORD>
  MONGO_USERNAME: <MONGO_USERNAME>
  MONGO_PASSWORD: <MONGO_PASSWORD>
