apiVersion: v1
kind: Secret
metadata:
  name: nexus-pull-secret
  namespace: {{ .Values.deployment.floopybird.namespace }}
  annotations:
    avp.kubernetes.io/path: "secrets/data/avp"
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "nexus.hdo3.local": {
          "auth": "<REPO_AUTH>"
        }
      }
    }
