---
- name: Install Docker on Ubuntu
  hosts: all
  become: true

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
          - python3-pip
        state: present


    - name: Add Docker's official GPG key using curl
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      become: true


    - name: Add Docker APT repository
      apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable'
        state: present


    - name: Install Docker and related packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started
        
    - name: Create "docker" group
      group:
        name: "docker"
        state: present


    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
        state: present
        
    - name: Inform user to log out and back in
      debug:
        msg: "You need to log out and back in for the group changes to take effect."         

          
          
          
