apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.7.9
  - vault-credentials.yaml
patches:
  - path: argocd-repo-server-deploy.yaml
  - path: argocd-cm.yaml
