apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
stringData:
  VAULT_ADDR: "https://vault.hdo3.local"
  VAULT_SKIP_VERIFY: "true"
  AVP_TYPE: "vault"
  AVP_AUTH_TYPE: "approle"
  AVP_ROLE_ID: "7d5e0ef4-8e44-14b0-39ba-91b97a1d3a73"
  AVP_SECRET_ID: "24d8f442-bb75-eb5a-0b59-b19a21436a90"
  AVP_KV_VERSION: "1"
