apiVersion: v2
name: floopybird
description: A Helm chart for the very original floopybird
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: mongodb
    version: "16.4.0"
    repository: "oci://registry-1.docker.io/bitnamicharts"
