apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: floopybird
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://git.hdo3.local/hdo3/k8s-manifests.git"
    targetRevision: HEAD
    path: application
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: helm_args
          value: "-f values.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: floopyfloopy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
